### ISSUE TITLE
Rewrite JWT Middleware

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#104]
Right now, we use `express-jwt` to validate the client's JWT. However, we do lots of configuration ourselves and there's some unwanted behavior. For example, if the JWT has expired, it will return with an `UNAUTHORIZED` error even if we actually want the API to return a `LOGIN_EXPIRED` action.

**Comment by nickbclifford** [comment]
Rolling our own JWT middleware entirely wouldn't be that hard, I've [done it before](https://github.com/nickbclifford/stem-summer-slide-backend/blob/master/src/utils/middleware.ts#L45), it's a lot easier to understand than `express-jwt`.

**Comment by nickbclifford** [comment]
Just learned that the `jsonwebtoken` library functions are actually [full synchronous under the hood](https://github.com/auth0/node-jsonwebtoken/issues/111), so using the async callback/promisified version is actually adding overhead. Something to keep in mind when I do the rewrite.
