### ISSUE TITLE
Switch Weather APIs

### ISSUE THREAD

**Issue by nickbclifford** [MyMICDS/MyMICDS-v2#132]
There's currently a low-severity security vulnerability present in the current version of `forecast.io` that we use.
![image](https://user-images.githubusercontent.com/11001606/69843234-3c6f2780-122c-11ea-9deb-3992388debf0.png)
That's not necessarily a huge deal, but `forecast.io` appears to not be maintained anymore (most recent commit was [last year](https://github.com/mateodelnorte/forecast.io/commit/8c3bef9f3b4a66159b04c0219ba3872b169bef90)). Dark Sky themselves has published a list of [endorsed API wrappers](https://darksky.net/dev/docs/libraries#libraries) that we should definitely look into.

**Comment by MeMeBigProgrammer** [comment]
Not only are we updating the version of API, but since [Dark Sky was acquired](https://blog.darksky.net/dark-sky-has-a-new-home/) by Apple, they will be discontinuing their API services in 2022. We should find an alternative now rather than later.

**Comment by MeMeBigProgrammer** [comment]
this has a list of possible weather APIs
https://github.com/n0shake/Public-APIs
