### ISSUE TITLE
MyMICDS Clubs

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#15]
Create a feature that allows people to create these "club" groups. They would be able to add other MyMICDS accounts to this group. Clubs could opt into have their club listed publicly on a page so other people could join. There would be a club page with a list of members and a chat room. Clubs could create meeting times, which could be automatically inserted into the user's schedule, or added to the user's planner.

**Comment by AsianPsychoBoy** [comment]
One of the most important uses would be paperless signup during club fairs
