### ISSUE TITLE
No Backround on Lunch

### ISSUE THREAD

**Issue by GrantBaum** [MyMICDS/MyMICDS-v2#198]
If it's Monday and you look at Tuesday's lunch, there is no black background making the text hard to read.

**Comment by MeMeBigProgrammer** [comment]
Could you attach a screenshot. I'm not seeing the same thing on my end.

**Comment by GrantBaum** [comment]
its on mobile only

**Comment by GrantBaum** [comment]
This may have been a one time thing. Im closing the issue.
