### ISSUE TITLE
Crash Reports when Website didn’t crash

### ISSUE THREAD

**Issue by GrantBaum** [MyMICDS/MyMICDS-v2#199]
I keep getting crash reports and closing them and the website still works fine. Idk if this is a problem with sentry or the backend API.

**Comment by nickbclifford** [comment]
I'm pretty sure this is a problem with Sentry, it treats any unhandled exception a crash. I believe this can be disabled in the Sentry init config on the frontend.

**Comment by GrantBaum** [comment]
I don't have sentry access, so can someone else take care of that, please?

**Comment by nickbclifford** [comment]
You should be able to change it [here](https://github.com/MyMICDS/MyMICDS-v2-Angular/blob/master/src/app/app.module.ts#L73), go ahead and send a pull request if you like.

**Comment by GrantBaum** [comment]
But if i change that and it does crash, does that not show the report?

**Comment by nickbclifford** [comment]
It will show in our Sentry dashboard, but not for the user, if that's what you're worried about. I believe the extra crash reports come from errors that Sentry catches, but aren't actually fatal.

**Comment by GrantBaum** [comment]
Just changed the code from true to false, submitted a pull request. I'm gonna close this since we resolved the issue.
