### ISSUE TITLE
Cache Portal / Canvas Feeds for Users

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#30]
When loading the schedule, one of the slowest things that bottlenecks the time of the API call is making a request to the portal/canvas every time the user wants to view their schedule or their planner. We could greatly speed up this process by caching the feeds in our database.

**Comment by nickbclifford** [comment]
Are you suggesting that we keep the whole feed in the database? If we were to do this, how often would we check if the feed has updated?

**Comment by michaelgira23** [comment]
I was imagining that we parse both the Portal and Canvas URL's, then store the schedule/event objects in the database. Canvas feeds will be more dynamic than portal feeds.

I'd say Portal could be queried every day or two. Maybe a week. Canvas URLs would want to be queried more often if we wanted to pursue #36. I don't know if 15 minutes/30 minutes/1 hour is too often? We could maybe have people opt-in to have their Canvas calendars queried more often, or query it more often depending on how active the user is.

For both of these feeds, I think we should have a button that allows for the user to manually trigger a feeds update though. For example, a "Refresh Canvas Events" on the Calendar, and maybe a "Refresh Portal Schedule" in settings page. This actually can solve #18 because we can have a queue to update Portal URLs. Every 15 minutes or so, the back-end can try querying a list of Portal URL's that need to be updated. If it's successful, then it would take it off the queue, otherwise try again in another 15 minutes.

Again, it might take a bit of playing around to see how often we can query the URLs without DDoSing the sites! AFAIK, there isn't any more graceful way to do this as Portal doesn't have an API. [Canvas API has webhooks](https://canvas.instructure.com/doc/api/webhooks_subscriptions.html), which may be a reason to check back with the school about the Canvas API.

**Comment by nickbclifford** [comment]
How exactly can we test this while the Portal URLs are still broken? (iirc)

**Comment by michaelgira23** [comment]
Well no, that's the thing. This can sort of _fix_ the brokenage of the Portal URLs. They work, but they don't _consistently_ work. By adding this queue system for the Portal URLs, we can just try again later in another 15 minutes if it isn't successful.

**Comment by nickbclifford** [comment]
Okay, so I'm assuming this means storing the time of the most recent query to refresh the URL?

**Comment by michaelgira23** [comment]
Doesn't necessarily, but that may be a good idea. I was just thinking about having something in `tasks.js` that fired every interval and fetched people's feeds. Either way, we might want to spread out requests as much as possible.

**Comment by nickbclifford** [comment]
Right, that's also what I was thinking—but how would we implement a queue without storing it?

**Comment by michaelgira23** [comment]
Merged in https://github.com/MyMICDS/MyMICDS-v2/pull/43
