### ISSUE TITLE
Unit/integration testing

### ISSUE THREAD

**Issue by nickbclifford** [MyMICDS/MyMICDS-v2#34]
I am aware that we _do_ have a `test` directory, but I think it would be in our best interest to start using [Mocha](http://mochajs.org/) or another framework for unit testing. Hopefully, this would stop us pushing broken stuff into production because we don't have the testing infrastructure.

**Comment by MiningPotatoes** [comment]
We could also probably start phasing the `test` directory into proper integration tests.

**Comment by nickbclifford** [comment]
Started in https://github.com/MyMICDS/MyMICDS-v2/commit/23726dc818ea64292552723ebd23eda358e0f569.
