### ISSUE TITLE
Enhance Registration Page

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#38]
The registration page could be a bit more engaging and streamline the entire setup from registration to integrating Portal/Canvas feeds and adding aliases. Right now, the URL inputs are a bit hidden in the settings page, so it could be cool if we could walk the user through setting everything up.

I think it would be great to have something like Slack does. ([Here's an example. I'm talking about the steps from confirming email to inviting users](https://www.useronboard.com/how-slack-onboards-new-users/)) Basically, have a full-page slideshow type thing. Have form inputs in the middle of the page with text to walk you though inserting data. Obviously, the user should be able to skip any of these additional steps besides basic account registration if they don't currently have time. We could give a little alert on the home page with a link to said walk-through page if the user hasn't already inserted their URLs or aliases yet.

**Comment by nickbclifford** [comment]
Shouldn't this be on the other repository?

**Comment by michaelgira23** [comment]
This is mainly a front-end issue. We may want to change the back-end API to submit data throughout the process in case the user leaves, but we can also just save the data in the front-end and only send the API request at the final step.

**Comment by michaelgira23** [comment]
Wait, my bad. I thought this was in the Angular repo already. Will move it to the front-end repo when I get the chance.
