### ISSUE TITLE
Background CORS Issue

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#40]
When selecting an image or generating a Trianglify background, it will keep uploading for a while. This happens both on production and on localhost.

While uploading on production, you get a CORS issue.

**This is the error message on Firefox:**
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.mymicds.net/background/upload. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
However the pre-flight OPTIONS request indeed contains `Access-Control-Allow-Origin: *` in the header and the actual POST request itself is made.

**This is the error message on Chrome:**
> POST https://api.mymicds.net/background/upload 504 (Gateway Time-out)
settings:1 XMLHttpRequest cannot load https://api.mymicds.net/background/upload. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mymicds.net' is therefore not allowed access. The response had HTTP status code 504.

While uploading on localhost, you just don't get a response.

**Comment by nickbclifford** [comment]
Have there been any recent changes to the backgrounds modules that may have caused this? How long has this been occurring for?

**Comment by michaelgira23** [comment]
To be honest, I have no idea. It was partially working since #27 but I haven't checked this summer. Maybe look into seeing if this is an nginx error if nothing pops up on the GitHub history?

**Comment by nickbclifford** [comment]
GitHub history proves worthless; I'll get to checking Nginx.

**Comment by michaelgira23** [comment]
The old nginx config is almost identical to the current nginx config, for both main `nginx.conf`, and mymicds.net and api.mymicds.net configs. Maybe it's because of an update to the `multer` package which handles the image upload stuff?

**Comment by michaelgira23** [comment]
Found the problem. Was caused by https://github.com/MyMICDS/MyMICDS-v2/commit/3b2bca45d2ba252f9337c5e7b29879be22f5c854 which got rid of the first parenthesis in the `background.upload` factory function in `backgroundAPI.js`
