### ISSUE TITLE
Add Notification System

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#42]
Add a notification system so we can alert our users. This should be completed first before we can finish #35 and #36. This could also help us send out mass emails like newsletters to our users. Naming of the notifications system should be generalized in case we complete MyMICDS Mobile and also want to give push notifications instead of email. The user should be able to turn on/off notifications in the settings page. It would also be useful to generate a hash so users can "unsubscribe" by visiting `https://mymicds.net/unsubscribe/{USER}/{HASH}` without entering their password, so this link can be put in the email.

**Comment by nickbclifford** [comment]
Would this involve two separate systems, i.e. one for mass emails that need to be sent to everyone and another for opt-in notifications like #35 and #36?

**Comment by michaelgira23** [comment]
I'm thinking this would all be under the same system. We could have different notification types though, so people could disable newsletters, formally dress days, new events on canvas, etc. independently.

**Comment by nickbclifford** [comment]
Currently, we don't use our notification system for anything other than announcements, but we do still have the system fully implemented, so I'm closing this.
