### ISSUE TITLE
Ability to hide all grade activity items

### ISSUE THREAD

**Issue by AsianPsychoBoy** [MyMICDS/MyMICDS-v2#57]
Currently, there are sometimes after-school events like sports or plays or other meetings that show up on the schedule. This messes with the percentage of the day and stuff.

**Comment by michaelgira23** [comment]
While it may be possible to remove events by looking at a user's feed and removing events that occur on the school-wide feed, I don't think this is necessary nor should we do it. I'm always hesitant to remove events from the portal feed when designing the schedule algorithm in case there's some weird event or some anomaly, and our mess-up makes someone late/miss class.

I know you were just talking specifically about the progress bar and percentage of the day, and I think what we've done before is just forcing the school day end to cap at 3:15 (allow it to go earlier in case there's a half-day or something). That way we keep the actual events in the schedule table, but percentages work has we intend them to. That might make this more of a front-end issue.

**Comment by michaelgira23** [comment]
Since we have two feeds for the new Veracross portal, the current schedule should only show classes now.
