### ISSUE TITLE
Fix middle school schedule

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#63]
>On today's late start, I notice for the seventh-grade schedule it says flex ends at 11:30, which isn't right, that's on normal days, and then for Physical Education it says that it ends at 11:10 and that Flex starts at 10:45. Also, it says recess starts at 12:05, and flex "ends" at 11:30. Hopefully, this made sense. Thanks. 

I thought there was another schedule problem too, though I forgot. Maybe I see if it's in our email.

**Comment by nickbclifford** [comment]
Not sure if this is still an issue, downgrading for now.
