### ISSUE TITLE
Start using Mongo aggregations

### ISSUE THREAD

**Issue by nickbclifford** [MyMICDS/MyMICDS-v2#67]
As seen in https://github.com/MyMICDS/MyMICDS-v2/commit/ff605a404f0bb0c46a8092ae0f983d0c2d4522d5, using aggregations instead of many consecutive database queries is much better for performance. There are some functions related to classes and planner events (according to @michaelgira23) that could benefit from this.

**Comment by michaelgira23** [comment]
Completed in #90.
