### ISSUE TITLE
Class Overlap/Merge to get rid of 1-minute classes

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#69]
Sometimes, this pops up in my schedule:
![capture](https://user-images.githubusercontent.com/6778537/34004708-3d1a3fd6-e0be-11e7-9593-6ff7e5e8ae8c.PNG)
The first "Collaborative" block is just 1 minute and the second identical block is the rest of the time. This should just be 12:10 to 12:50.

My guess is that it has something to do with the [`ordineSchedule()` function in the `schedule` lib](https://github.com/MyMICDS/MyMICDS-v2/blob/master/src/libs/schedule.js#L604). There might be two different collaborative periods that show up in separate calendar feeds (one for general block schedule collab, then another one for the specific day or something) and the `ordineSchedule()` function is not overlapping the classes properly which creates the 1-minute class. However, this is just speculation and further analysis is required.

**Comment by nickbclifford** [comment]
I can confirm that my personal Portal feed shows Collab as starting at 12:11. ![Image](https://i.imgur.com/Xie0b1Y.jpg)

**Comment by michaelgira23** [comment]
Perhaps we can have a custom algorithm that checks if there's any class that is under 5 minutes long, and if theres an adjacent class with the same name, it simply merges them?

**Comment by michaelgira23** [comment]
Hopefully this is fixed with Veracross. As always, the best way to fix your problems is to avoid them.
