### ISSUE TITLE
Day Rotation Broke

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#75]
Getting schedule day rotation is broken and only returns null and we need to not.

**Comment by michaelgira23** [comment]
However, it seems that the day rotation still works on the planner, meaning it's only broken when trying to get the day of a specific date.

**Comment by AsianPsychoBoy** [comment]
understandable, have a nice day

**Comment by michaelgira23** [comment]
Further investigation yields that this only happens when I am logged in. The day rotation format might have changed for personal schedules, which would explain why the planner day rotation works but not the schedule for a specific user.

We might be able to fix the problem by just getting day rotation from the global calendar no matter what.
