### ISSUE TITLE
Weather update broke

### ISSUE THREAD

**Issue by nickbclifford** [MyMICDS/MyMICDS-v2#77]
Sending `POST /weather/update` to the API (on `upgrade-api` branch) causes a cryptic error to be thrown by some node module. I don't think we're directly using it anyway, so we might have to do some digging.

![image](https://user-images.githubusercontent.com/11001606/37556786-d8d4ad50-29c8-11e8-86d2-e779ea293785.png)

**Comment by michaelgira23** [comment]
Looks like it works fine when the function is called in the tasks server--this error only happens when manually trigger a weather update from the API call

**Comment by nickbclifford** [comment]
I just took a look at this, turns out the error is coming from [this line](https://github.com/MyMICDS/MyMICDS-v2/blob/master/src/routes/weatherAPI.js#L20). For some reason, I can't manage to reproduce this on `promisify`, even though it's still broken on `master` and the socket.io dependency is on the same version.
