### ISSUE TITLE
Add Daily Bulletin date santiy checks

### ISSUE THREAD

**Issue by michaelgira23** [MyMICDS/MyMICDS-v2#88]
Sometimes, bulletins are sent out with a different year or month. Add sanity checks and automatically correct when bulletin date should be a different year.

**Comment by nickbclifford** [comment]
I think technically the implementation of the new daily bulletin date format in https://github.com/MyMICDS/MyMICDS-v2/commit/37965b156aaac1acd965a83de474a53d300a0dd7 fixes this, at least for years. Going to close this for now unless we get issues with months.
